apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
  labels:
    app: websiteapp
    tier: database
    service: database
    color: blue
data:
  POSTGRES_DB: "#{database}#"
  POSTGRES_USER: "#{user}#"
  POSTGRES_PASSWORD: "#{password}#"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: website-config
  labels:
    app: websiteapp
    tier: website
    service: website
    color: green
data:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: https://+:443;http://+:80
  