apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  replicas: 1
  selector:
    matchLabels:
      type: website
      service: website
      color: green
  minReadySeconds: 1
  progressDeadlineSeconds: 60
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        type: website
        service: website
        color: green
        language: csharp
    spec:
      imagePullSecrets:
      - name: repo
      containers:
      - name: website
        image: #{image}#
        ports:
        - containerPort: 8080
          name: website
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: /
            port: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: website
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    type: website
    service: website
    color: green

---