apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: "#{database}#"
  POSTGRES_USER: "#{user}#"
  POSTGRES_PASSWORD: "#{password}#"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "https://+:443;http://+:80"
  ASPNETCORE_Kestrel__Certificates__Default__Password: "#{certPassword}#"
  ASPNETCORE_Kestrel__Certificates__Default__Path: "https/Majunga.Server.pfx"
  