apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongovolume
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage

---  
 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlitevolume
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websiteapp
      tier: website
      service: website
      color: green
  minReadySeconds: 1
  progressDeadlineSeconds: 60
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: websiteapp
        tier: website
        service: website
        color: green
        language: csharp
    spec:      
      imagePullSecrets:
        - name: repo
      volumes:
      - name: sqlitevolume
        persistentVolumeClaim:
          claimName: sqlitevolume
      containers:
      - name: website
        image: #{image}#
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        volumeMounts:
        - mountPath: "/app/Data"
          name: sqlitevolume
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
          - name: ASPNETCORE_URLS
            value: "https://+:443;http://+:80"
          - name: ASPNETCORE_Kestrel__Certificates__Default__Password
            value: "#{certPassword}#"
          - name: ASPNETCORE_Kestrel__Certificates__Default__Path
            value: "https/Majunga.Server.pfx"

---

apiVersion: v1
kind: Service
metadata:
  name: website
spec:
  type: LoadBalancer
  ports:
  - port: 443
    name: https
  - port: 80
    name: http
  selector:
    app: websiteapp
    tier: website
    service: website
    color: green

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websiteapp
      tier: database
      service: mongodb
      color: blue
  minReadySeconds: 1
  progressDeadlineSeconds: 60
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: websiteapp
        tier: database
        service: mongodb
        color: blue
    spec:
      imagePullSecrets:
      - name: repo
      volumes:
      - name: mongovolume
        persistentVolumeClaim:
          claimName: mongovolume
      containers:
      - name: mongodb
        volumeMounts:
        - name: mongovolume
          mountPath: /data/db
        image: mongo:latest
        ports:
        - containerPort: 27017

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  type: NodePort
  ports:
  - port: 27017
  selector:
    app: websiteapp
    tier: database
    service: mongodb
    color: blue

---
