apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongovolume
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage

---  
 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlitevolume
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
  
---
